btc-leader-2:
    restart: always
    image: jvlythical/bitcoind
    volumes:
        - ./volumes/node-2:/bitcoin/.bitcoin/regtest
        #- ./btc_init:/usr/local/bin/btc_init
        - ./../../build/src:/sbin/bitcoin
    container_name: btc-leader-2
    cpu_shares: 100 
